//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreatheEasyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadgeMilestone
    {
        public int BadgeID { get; set; }
        public int DaysIn { get; set; }
        public int ImageActiveID { get; set; }
        public int ImageInactiveID { get; set; }
    
        public virtual Image ImageActive { get; set; }
        public virtual Image ImageInactive { get; set; }
    }
}
