//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreatheEasyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthFactMilestone
    {
        public int ID { get; set; }
        public Nullable<decimal> DaysIn { get; set; }
        public string FactBody { get; set; }
    }
}
