//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreatheEasyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.UserMilestones = new HashSet<UserMilestone>();
            this.Cravings = new HashSet<Craving>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public decimal PricePerPack { get; set; }
        public int CigsPerDay { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> FinalQuitDate { get; set; }
        public int PlanID { get; set; }
        public string GoalItem { get; set; }
        public Nullable<decimal> GoalPrice { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Plan Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMilestone> UserMilestones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Craving> Cravings { get; set; }
    }
}
